/* ════════════════════════════════════════════════════════════════
   renderers.js — production-grade output renderer
   Outputs: OpenAPI JSON/YAML, Markdown, Static HTML, Postman, Drift
════════════════════════════════════════════════════════════════ */

function renderAll(scan) {
  const openapi = toOpenApi(scan);
  const openapiJson = JSON.stringify(openapi, null, 2);
  const openapiYaml = toYaml(openapi);
  return {
    openapiJson:  { content: openapiJson,              type: "application/json; charset=utf-8" },
    openapiYaml:  { content: openapiYaml,              type: "application/yaml; charset=utf-8" },
    markdown:     { content: toMarkdown(scan),         type: "text/markdown; charset=utf-8" },
    html:         { content: toHtml(scan, openapiJson), type: "text/html; charset=utf-8" },
    drift:        { content: JSON.stringify(scan.drift, null, 2), type: "application/json; charset=utf-8" },
    postman:      { content: JSON.stringify(toPostman(scan), null, 2), type: "application/json; charset=utf-8" }
  };
}

/* ─────────────────────────────────────────────
   OPENAPI 3.1
───────────────────────────────────────────── */
function toOpenApi(scan) {
  const spec = {
    openapi: "3.1.0",
    info: {
      title: scan.title || "Generated API",
      version: scan.version || "1.0.0",
      description: scan.description || "Generated by Smart API Documentation Generator."
    },
    servers: [{ url: (scan.baseUrl || "http://localhost") + "/api", description: "API base" }],
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" }
      }
    },
    paths: {}
  };

  for (const ep of scan.endpoints) {
    spec.paths[ep.path] ||= {};
    const parameters = [
      ...ep.request.pathParams.map(p => param(p, "path")),
      ...ep.request.queryParams.map(p => param(p, "query")),
      ...ep.request.headers.filter(h => !/authorization/i.test(h.name)).map(h => ({
        name: h.name, in: "header",
        required: Boolean(h.required), description: h.description,
        schema: { type: "string" }
      }))
    ];

    const op = {
      operationId: ep.operationId,
      summary: ep.summary,
      description: [
        ep.description,
        ep.controller ? `**Controller:** \`${ep.controller}@${ep.action}\`` : "",
        ep.middleware && ep.middleware.length ? `**Middleware:** ${ep.middleware.join(", ")}` : "",
        `*Source: ${ep.sourceFile}:${ep.sourceLine}*`
      ].filter(Boolean).join("\n\n"),
      tags: ep.tags,
      deprecated: ep.deprecated,
      parameters,
      responses: Object.fromEntries(ep.responses.map(r => [String(r.status), {
        description: r.description,
        content: r.schema ? { "application/json": { schema: stripRequiredFlags(r.schema) } } : undefined
      }]))
    };

    if (ep.request.body?.required) {
      const bodyProps = ep.request.body.schema.properties || {};
      op.requestBody = {
        required: true,
        content: {
          [ep.request.body.contentType || "application/json"]: {
            schema: {
              type: "object",
              properties: Object.fromEntries(
                Object.entries(bodyProps).map(([name, field]) => [name, stripRequiredFlags(field)])
              ),
              required: Object.entries(bodyProps).filter(([, f]) => f.required).map(([n]) => n)
            }
          }
        }
      };
    }

    if (ep.authRequired) op.security = [{ bearerAuth: [] }];
    spec.paths[ep.path][ep.method.toLowerCase()] = op;
  }
  return spec;
}

function param(p, location) {
  return {
    name: p.name, in: location,
    required: location === "path" ? true : Boolean(p.required),
    description: p.description,
    schema: { type: p.type || "string", ...(p.format ? { format: p.format } : {}) }
  };
}

function stripRequiredFlags(schema) {
  if (!schema || typeof schema !== "object") return schema;
  const copy = Array.isArray(schema) ? [] : {};
  for (const [key, value] of Object.entries(schema)) {
    if (key === "required" && typeof value === "boolean") continue;
    copy[key] = stripRequiredFlags(value);
  }
  return copy;
}

/* ─────────────────────────────────────────────
   MARKDOWN
───────────────────────────────────────────── */
function toMarkdown(scan) {
  const L = [];
  const push = (...lines) => lines.forEach(l => L.push(l));

  push(`# ${scan.title} — API Documentation`, "");
  push(`> Generated: ${scan.generatedAt}  `);
  push(`> Base URL: \`${scan.baseUrl || "http://localhost"}/api\``, "");
  push("## Project Overview", "");
  push(`| Property | Value |`, `| --- | --- |`);
  push(`| Project | ${scan.title} |`);
  push(`| Version | ${scan.version || "1.0.0"} |`);
  push(`| Languages | ${(scan.project.languages || []).join(", ") || "—"} |`);
  push(`| Frameworks | ${(scan.project.frameworks || []).filter(f => !f.startsWith("CORS")).join(", ") || "—"} |`);
  push(`| Files scanned | ${scan.files.length} |`);
  push(`| Endpoints found | ${scan.endpoints.length} |`);
  push("");

  /* Auth section */
  push("## Authentication", "");
  push("This API uses **JWT Bearer token** authentication (`tymon/jwt-auth`).", "");
  push("Include the token in every protected request:", "");
  push("```", "Authorization: Token <your-jwt-token>", "```", "");
  push("### Login Flow", "");
  push("1. Call `POST /api/users/login` with `user.email` and `user.password`.");
  push("2. Receive a `user.token` in the response.");
  push("3. Store the token and attach it as `Authorization: Token <token>` on subsequent requests.", "");

  /* Endpoint summary table */
  push("## Endpoint Summary", "");
  push("| Method | Path | Summary | Controller | Auth | Middleware |");
  push("| --- | --- | --- | --- | --- | --- |");
  for (const ep of scan.endpoints) {
    const ctrl = ep.controller ? `${ep.controller}@${ep.action}` : "—";
    const mw = (ep.middleware || []).join(", ") || "—";
    push(`| ${ep.method} | \`${ep.path}\` | ${ep.summary} | ${ctrl} | ${ep.authRequired ? "✓" : "—"} | ${mw} |`);
  }
  push("");

  /* Per-endpoint detail */
  push("## Endpoint Reference", "");
  for (const ep of scan.endpoints) {
    push(`### ${ep.method} \`${ep.path}\``, "");
    push(`**${ep.summary}**`, "");
    push(ep.description, "");
    push(`| Property | Value |`, `| --- | --- |`);
    push(`| Operation ID | \`${ep.operationId}\` |`);
    push(`| Tags | ${ep.tags.join(", ")} |`);
    push(`| Auth required | ${ep.authRequired ? "Yes (Bearer JWT)" : "No"} |`);
    if (ep.controller) push(`| Controller | \`${ep.controller}@${ep.action}\` |`);
    if (ep.middleware && ep.middleware.length) push(`| Middleware | ${ep.middleware.join(", ")} |`);
    push(`| Source | \`${ep.sourceFile}:${ep.sourceLine}\` |`);
    push("");

    /* Request params */
    const allParams = [
      ...ep.request.pathParams.map(p => ["path", p.name, p.type, "Yes", p.description]),
      ...ep.request.queryParams.map(p => ["query", p.name, p.type, p.required ? "Yes" : "No", p.description]),
      ...ep.request.headers.map(h => ["header", h.name, "string", h.required ? "Yes" : "No", h.description || ""])
    ];
    if (allParams.length) {
      push("#### Request Parameters", "");
      mdTable(L, ["Location", "Name", "Type", "Required", "Description"], allParams);
      push("");
    }

    /* Body fields */
    const bodyFields = Object.entries(ep.request.body?.schema?.properties || {});
    if (bodyFields.length) {
      push("#### Request Body", "");
      push(`Content-Type: \`${ep.request.body.contentType}\``, "");
      mdTable(L, ["Field", "Type", "Required", "Validation Rules", "Example", "Description"],
        bodyFields.map(([name, f]) => [
          name, f.type, f.required ? "Yes" : "No",
          Array.isArray(f.validationRules) ? f.validationRules.join(", ") : (f.validationRules || ""),
          JSON.stringify(f.example ?? ""), f.description || ""
        ])
      );
      push("");
      push("**Sample request body:**", "");
      const sample = Object.fromEntries(bodyFields.map(([n, f]) => [n, f.example !== undefined ? f.example : f.type]));
      push("```json", JSON.stringify({ [ep.tags[0] || "data"]: sample }, null, 2), "```", "");
    }

    /* Responses */
    push("#### Responses", "");
    mdTable(L, ["Status", "Description"], ep.responses.map(r => [String(r.status), r.description]));
    push("");

    /* Sample cURL */
    push("#### cURL Example", "");
    const curlLines = [`curl -X ${ep.method} "http://localhost/api${ep.path}"`];
    if (ep.authRequired) curlLines.push('  -H "Authorization: Token <your-jwt-token>"');
    curlLines.push('  -H "Content-Type: application/json"');
    if (bodyFields.length && ["POST", "PUT", "PATCH"].includes(ep.method)) {
      const sample = Object.fromEntries(bodyFields.map(([n, f]) => [n, f.example !== undefined ? f.example : f.type]));
      curlLines.push(`  -d '${JSON.stringify({ [ep.tags[0] || "data"]: sample })}'`);
    }
    push("```bash", curlLines.join(" \\\n"), "```", "");

    /* Error codes */
    if (ep.errorCodes && ep.errorCodes.length) {
      push("#### Error Codes", "");
      mdTable(L, ["Code", "Message", "Resolution"], ep.errorCodes.map(e => [e.code, e.message, e.resolution]));
      push("");
    }
    push("---", "");
  }

  /* Drift */
  push("## Drift Report", "");
  push(`| Metric | Count |`, `| --- | --- |`);
  push(`| New in code (undocumented) | ${scan.drift.newInCode.length} |`);
  push(`| Removed from spec | ${scan.drift.removedFromSpec.length} |`);
  push(`| Changed signatures | ${scan.drift.changed.length} |`);
  push(`| In sync | ${scan.drift.inSync.length} |`);

  return L.join("\n");
}

function mdTable(lines, headers, rows) {
  lines.push(`| ${headers.join(" | ")} |`);
  lines.push(`| ${headers.map(() => "---").join(" | ")} |`);
  if (!rows.length) {
    lines.push(`| ${headers.map((_, i) => i === 0 ? "—" : "").join(" | ")} |`);
    return;
  }
  for (const row of rows) lines.push(`| ${row.map(v => String(v ?? "").replace(/\|/g, "\\|")).join(" | ")} |`);
}

/* ─────────────────────────────────────────────
   STATIC HTML — rich, production-grade UI
   Dark sidebar + content area layout
   Full section coverage matching requirements
───────────────────────────────────────────── */
function toHtml(scan, openapiJson) {
  const E = escapeHtml;
  const endpointsJson = E(JSON.stringify(scan.endpoints));
  const scanJson = E(JSON.stringify({
    title: scan.title, version: scan.version, description: scan.description,
    baseUrl: scan.baseUrl, generatedAt: scan.generatedAt, project: scan.project,
    endpoints: scan.endpoints, drift: scan.drift, authMatrix: scan.authMatrix || {}
  }));

  /* Group endpoints by tag for sidebar */
  const byTag = {};
  for (const ep of scan.endpoints) {
    const tag = (ep.tags || ["other"])[0];
    (byTag[tag] = byTag[tag] || []).push(ep);
  }

  /* Status badge colours */
  const statusColor = s => s < 300 ? "#16a34a" : s < 400 ? "#0369a1" : s < 500 ? "#d97706" : "#dc2626";

  /* Build all endpoint detail panels */
  const panels = scan.endpoints.map((ep, i) => {
    const id = `ep-${i}`;
    const bodyFields = Object.entries(ep.request.body?.schema?.properties || {});
    const allParams = [
      ...ep.request.pathParams.map(p => ({ loc: "path", ...p })),
      ...ep.request.queryParams.map(p => ({ loc: "query", ...p })),
      ...ep.request.headers.map(h => ({ loc: "header", name: h.name, type: "string", required: h.required, description: h.description }))
    ];

    const sampleBody = bodyFields.length
      ? JSON.stringify({ [ep.tags[0] || "data"]: Object.fromEntries(bodyFields.map(([n, f]) => [n, f.example !== undefined ? f.example : f.type])) }, null, 2)
      : "";

    const curlLines = [`curl -X ${ep.method} "${scan.baseUrl || "http://localhost"}/api${ep.path}"`];
    if (ep.authRequired) curlLines.push('  -H "Authorization: Token &lt;your-jwt-token&gt;"');
    curlLines.push('  -H "Content-Type: application/json" \\');
    if (sampleBody && ["POST", "PUT", "PATCH"].includes(ep.method)) {
      curlLines.push(`  -d '${E(sampleBody)}'`);
    }

    return `
<article class="ep-panel" id="${id}" style="display:none">
  <div class="ep-header">
    <span class="badge method ${ep.method}">${ep.method}</span>
    <code class="ep-path">${E(ep.path)}</code>
    ${ep.deprecated ? '<span class="pill dep">Deprecated</span>' : ""}
    ${ep.authRequired ? '<span class="pill auth">🔒 Auth required</span>' : '<span class="pill open">Public</span>'}
  </div>
  <p class="ep-desc">${E(ep.description)}</p>

  <div class="info-grid">
    <div class="info-cell"><div class="info-label">Operation ID</div><code>${E(ep.operationId)}</code></div>
    <div class="info-cell"><div class="info-label">Tag</div><span>${E((ep.tags || []).join(", "))}</span></div>
    ${ep.controller ? `<div class="info-cell"><div class="info-label">Controller</div><code>${E(ep.controller)}@${E(ep.action)}</code></div>` : ""}
    ${ep.middleware && ep.middleware.length ? `<div class="info-cell"><div class="info-label">Middleware</div><code>${ep.middleware.map(E).join(", ")}</code></div>` : ""}
    <div class="info-cell"><div class="info-label">Source</div><code style="font-size:11px">${E(ep.sourceFile)}:${ep.sourceLine}</code></div>
    <div class="info-cell"><div class="info-label">Confidence</div><span class="conf-bar"><span style="width:${Math.round(ep.confidence * 100)}%"></span></span> ${Math.round(ep.confidence * 100)}%</div>
  </div>

  ${allParams.length ? `
  <section class="ep-section">
    <h3>Parameters</h3>
    <table class="param-table">
      <thead><tr><th>Location</th><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr></thead>
      <tbody>
        ${allParams.map(p => `
          <tr>
            <td><span class="pill loc-${p.loc}">${p.loc}</span></td>
            <td><code>${E(p.name)}</code></td>
            <td>${E(p.type || "string")}</td>
            <td>${p.required ? '<span class="req-yes">Yes</span>' : '<span class="req-no">No</span>'}</td>
            <td>${E(p.description || "")}</td>
          </tr>`).join("")}
      </tbody>
    </table>
  </section>` : ""}

  ${bodyFields.length ? `
  <section class="ep-section">
    <h3>Request Body <small>Content-Type: application/json</small></h3>
    <table class="param-table">
      <thead><tr><th>Field</th><th>Type</th><th>Required</th><th>Validation</th><th>Example</th><th>Description</th></tr></thead>
      <tbody>
        ${bodyFields.map(([name, f]) => `
          <tr>
            <td><code>${E(name)}</code></td>
            <td>${E(f.type || "string")}</td>
            <td>${f.required ? '<span class="req-yes">Yes</span>' : '<span class="req-no">No</span>'}</td>
            <td><span class="rules">${(Array.isArray(f.validationRules) ? f.validationRules : []).map(E).join(" · ") || "—"}</span></td>
            <td><code>${E(JSON.stringify(f.example ?? ""))}</code></td>
            <td>${E(f.description || "")}</td>
          </tr>`).join("")}
      </tbody>
    </table>
    <div class="code-block-wrap">
      <div class="code-label">Sample request</div>
      <pre class="codebox">${E(sampleBody)}</pre>
    </div>
  </section>` : ""}

  <section class="ep-section">
    <h3>Responses</h3>
    <div class="response-list">
      ${ep.responses.map(r => `
        <div class="response-row">
          <span class="status-badge" style="background:${statusColor(r.status)}20;color:${statusColor(r.status)};border:1px solid ${statusColor(r.status)}40">${r.status}</span>
          <span>${E(r.description)}</span>
        </div>`).join("")}
    </div>
  </section>

  <section class="ep-section">
    <h3>cURL</h3>
    <div class="code-block-wrap">
      <pre class="codebox">${curlLines.join(" \\\n")}</pre>
    </div>
  </section>

  ${ep.errorCodes && ep.errorCodes.length ? `
  <section class="ep-section">
    <h3>Error Codes</h3>
    <table class="param-table">
      <thead><tr><th>Code</th><th>Message</th><th>Resolution</th></tr></thead>
      <tbody>
        ${ep.errorCodes.map(e => `<tr><td><code>${E(e.code)}</code></td><td>${E(e.message)}</td><td>${E(e.resolution)}</td></tr>`).join("")}
      </tbody>
    </table>
  </section>` : ""}
</article>`;
  }).join("\n");

  /* Build sidebar nav groups */
  const navGroups = Object.entries(byTag).map(([tag, eps]) => `
    <div class="nav-group">
      <div class="nav-group-title">${E(tag)}</div>
      ${eps.map((ep, _) => {
        const i = scan.endpoints.indexOf(ep);
        return `<button class="nav-ep" data-ep="${i}" onclick="showEp(${i})">
          <span class="nav-method ${ep.method}">${ep.method}</span>
          <span class="nav-path">${E(ep.path)}</span>
        </button>`;
      }).join("")}
    </div>`).join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${E(scan.title)} — API Docs</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Syne:wght@600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<style>
:root{--bg:#0d1117;--surface:#161b22;--surface2:#21262d;--border:#30363d;--text:#e6edf3;--muted:#8b949e;--accent:#58a6ff;--accent2:#3fb950;--warn:#d29922;--danger:#f85149;--radius:8px;--mono:'IBM Plex Mono',monospace;--sans:'Inter',sans-serif;--display:'Syne',sans-serif}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:var(--sans);background:var(--bg);color:var(--text);display:flex;flex-direction:column;min-height:100vh;font-size:14px}
a{color:var(--accent);text-decoration:none}
code{font-family:var(--mono);font-size:12px;background:#1f2937;padding:2px 6px;border-radius:4px;color:#a5b4fc}
pre.codebox{font-family:var(--mono);font-size:12px;background:#0d1117;border:1px solid var(--border);border-radius:var(--radius);padding:14px;overflow:auto;line-height:1.7;color:#c9d1d9;white-space:pre-wrap;word-break:break-all}
/* ── Top bar ── */
.topbar{background:var(--surface);border-bottom:1px solid var(--border);padding:0 24px;display:flex;align-items:center;gap:20px;height:56px;position:sticky;top:0;z-index:100}
.topbar-logo{font-family:var(--display);font-size:17px;font-weight:700;color:var(--text);white-space:nowrap}
.topbar-logo span{color:var(--accent)}
.topbar-meta{color:var(--muted);font-size:12px;border-left:1px solid var(--border);padding-left:16px}
.topbar-right{margin-left:auto;display:flex;gap:10px;align-items:center}
.topbar-btn{background:var(--surface2);border:1px solid var(--border);color:var(--text);padding:6px 14px;border-radius:var(--radius);cursor:pointer;font-size:12px;font-family:var(--sans)}
.topbar-btn:hover{background:#2d333b}
/* ── Layout ── */
.layout{display:flex;flex:1;overflow:hidden;height:calc(100vh - 56px)}
/* ── Sidebar ── */
.sidebar{width:260px;min-width:260px;background:var(--surface);border-right:1px solid var(--border);overflow-y:auto;display:flex;flex-direction:column}
.sidebar-search{padding:12px;border-bottom:1px solid var(--border)}
.sidebar-search input{width:100%;background:#0d1117;border:1px solid var(--border);color:var(--text);padding:7px 10px;border-radius:var(--radius);font-size:12px;font-family:var(--sans)}
.sidebar-search input::placeholder{color:var(--muted)}
.sidebar-section{padding:8px 0}
.sidebar-section-title{font-size:10px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);padding:6px 14px}
.nav-group{margin-bottom:4px}
.nav-group-title{font-size:11px;font-weight:600;color:var(--muted);padding:6px 14px 4px;text-transform:uppercase;letter-spacing:.05em}
.nav-ep{display:flex;align-items:center;gap:7px;width:100%;background:none;border:none;cursor:pointer;padding:5px 14px;text-align:left;border-radius:0;transition:background .1s}
.nav-ep:hover,.nav-ep.active{background:#1f2937}
.nav-path{font-size:12px;color:var(--text);font-family:var(--mono);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}
.nav-method{font-size:10px;font-weight:700;min-width:46px;text-align:center;padding:2px 5px;border-radius:4px;color:#fff;flex-shrink:0}
/* ── Sidebar quick nav ── */
.sb-quick{border-bottom:1px solid var(--border);padding:0}
.sb-quick button{display:block;width:100%;text-align:left;background:none;border:none;color:var(--muted);font-size:12px;padding:8px 14px;cursor:pointer;font-family:var(--sans)}
.sb-quick button:hover{color:var(--accent);background:#1f2937}
/* ── Main content ── */
.main{flex:1;overflow-y:auto;padding:0}
.main-inner{max-width:960px;margin:0 auto;padding:32px 28px}
/* ── Section cards ── */
.section-card{background:var(--surface);border:1px solid var(--border);border-radius:12px;margin-bottom:24px;overflow:hidden}
.section-card-head{padding:18px 22px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:10px}
.section-card-head h2{font-family:var(--display);font-size:15px;font-weight:700}
.section-icon{width:28px;height:28px;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:14px}
.section-body{padding:20px 22px}
/* ── Stat grid ── */
.stat-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}
.stat-card{background:#0d1117;border:1px solid var(--border);border-radius:var(--radius);padding:16px}
.stat-num{font-family:var(--display);font-size:28px;font-weight:700;line-height:1}
.stat-label{font-size:11px;color:var(--muted);margin-top:4px}
/* ── Method badge ── */
.badge.method,.nav-method{font-family:var(--mono);font-weight:700}
.badge{display:inline-flex;align-items:center;justify-content:center;padding:4px 10px;border-radius:5px;font-size:11px;font-weight:700;letter-spacing:.02em}
.GET,.nav-method.GET{background:#0d3b1e;color:#3fb950;border:1px solid #196c2e}
.POST,.nav-method.POST{background:#0c2d5c;color:#58a6ff;border:1px solid #1158c7}
.PUT,.nav-method.PUT,.PATCH,.nav-method.PATCH{background:#3b2500;color:#d29922;border:1px solid #7d4b00}
.DELETE,.nav-method.DELETE{background:#3b0d0d;color:#f85149;border:1px solid #8c1a1a}
.OPTIONS,.nav-method.OPTIONS,.HEAD,.nav-method.HEAD{background:#1f1f1f;color:#8b949e;border:1px solid #30363d}
/* ── Pills ── */
.pill{display:inline-block;font-size:11px;padding:2px 8px;border-radius:999px;font-family:var(--sans);font-weight:500}
.pill.auth{background:#162032;color:var(--accent);border:1px solid #1b3a5c}
.pill.open{background:#0d2e13;color:var(--accent2);border:1px solid #1a5c2a}
.pill.dep{background:#3b2500;color:#d29922;border:1px solid #7d4b00}
.pill.loc-path{background:#1a1060;color:#a78bfa;border:1px solid #3b1fc4}
.pill.loc-query{background:#0d2e20;color:#34d399;border:1px solid #065f46}
.pill.loc-header{background:#1a1010;color:#f87171;border:1px solid #7f1d1d}
/* ── Endpoint panels ── */
.ep-header{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:16px}
.ep-path{font-size:15px;font-weight:500;color:var(--text)}
.ep-desc{color:var(--muted);line-height:1.6;margin-bottom:18px;font-size:13px}
.info-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:10px;margin-bottom:18px}
.info-cell{background:#0d1117;border:1px solid var(--border);border-radius:var(--radius);padding:10px 12px}
.info-label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin-bottom:4px}
.conf-bar{display:inline-block;width:60px;height:5px;background:#21262d;border-radius:3px;vertical-align:middle;margin-right:4px;overflow:hidden}
.conf-bar span{display:block;height:100%;background:var(--accent2);border-radius:3px}
/* ── Tables ── */
.param-table{width:100%;border-collapse:collapse;font-size:12px}
.param-table th{background:#0d1117;color:var(--muted);font-weight:600;text-align:left;padding:8px 10px;border-bottom:1px solid var(--border);font-size:11px;text-transform:uppercase;letter-spacing:.05em}
.param-table td{padding:8px 10px;border-bottom:1px solid #21262d;vertical-align:top;color:var(--text)}
.param-table tr:last-child td{border-bottom:0}
.req-yes{color:var(--accent2);font-weight:600}
.req-no{color:var(--muted)}
.rules{color:var(--warn);font-family:var(--mono);font-size:11px}
/* ── Response list ── */
.response-list{display:flex;flex-direction:column;gap:6px}
.response-row{display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid #21262d}
.response-row:last-child{border-bottom:0}
.status-badge{font-family:var(--mono);font-size:12px;font-weight:700;padding:3px 10px;border-radius:5px;min-width:52px;text-align:center}
/* ── Section headers ── */
.ep-section{margin-top:22px;padding-top:18px;border-top:1px solid var(--border)}
.ep-section h3{font-size:13px;font-weight:600;color:var(--text);margin-bottom:10px;display:flex;align-items:center;gap:6px}
.ep-section h3 small{font-size:11px;color:var(--muted);font-weight:400}
/* ── Code block ── */
.code-block-wrap{position:relative;margin-top:10px}
.code-label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);padding:6px 12px;background:#161b22;border:1px solid var(--border);border-bottom:0;border-radius:var(--radius) var(--radius) 0 0}
/* ── Overview sections ── */
.overview-section{margin-bottom:24px}
.tag-summary{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}
.tag-chip{background:var(--surface2);border:1px solid var(--border);border-radius:6px;padding:6px 12px;font-size:12px;cursor:pointer;display:flex;align-items:center;gap:6px}
.tag-chip:hover{border-color:var(--accent)}
.tag-count{font-weight:700;color:var(--accent)}
/* ── Auth section ── */
.auth-flow{background:#0d1117;border:1px solid var(--border);border-radius:var(--radius);padding:16px;margin-top:10px}
.auth-step{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid #21262d}
.auth-step:last-child{border-bottom:0}
.auth-step-num{width:26px;height:26px;background:var(--accent);color:#0d1117;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:12px;flex-shrink:0}
.auth-step-body{flex:1}
.auth-step-title{font-weight:600;font-size:13px;margin-bottom:2px}
.auth-step-desc{font-size:12px;color:var(--muted);line-height:1.5}
/* ── Error table ── */
.error-table{width:100%;border-collapse:collapse;font-size:12px}
.error-table th,.error-table td{padding:8px 12px;border-bottom:1px solid #21262d;text-align:left}
.error-table th{color:var(--muted);font-size:11px;text-transform:uppercase;font-weight:600;background:#0d1117}
/* ── Drift report ── */
.drift-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}
.drift-card{border:1px solid var(--border);border-radius:var(--radius);padding:14px}
.drift-num{font-size:24px;font-weight:700}
.drift-label{font-size:11px;color:var(--muted);margin-top:4px}
/* ── Env table ── */
.env-table{width:100%;border-collapse:collapse;font-size:12px}
.env-table th,.env-table td{padding:8px 12px;border-bottom:1px solid #21262d;text-align:left}
.env-table th{color:var(--muted);font-size:11px;text-transform:uppercase;background:#0d1117}
/* ── Filter bar ── */
.filter-bar{display:flex;gap:8px;flex-wrap:wrap;padding:14px 22px;border-bottom:1px solid var(--border);background:var(--surface);position:sticky;top:0;z-index:10}
.filter-btn{background:var(--surface2);border:1px solid var(--border);color:var(--muted);padding:5px 12px;border-radius:var(--radius);cursor:pointer;font-size:11px;font-family:var(--sans);font-weight:600}
.filter-btn:hover,.filter-btn.active{background:#1f2937;color:var(--text)}
.filter-search{flex:1;min-width:160px;background:#0d1117;border:1px solid var(--border);color:var(--text);padding:6px 10px;border-radius:var(--radius);font-family:var(--sans);font-size:12px}
/* ── Endpoint list (overview table) ── */
.ep-list-table{width:100%;border-collapse:collapse;font-size:12px}
.ep-list-table th{background:#0d1117;color:var(--muted);font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.05em;padding:8px 12px;border-bottom:1px solid var(--border);text-align:left}
.ep-list-table td{padding:9px 12px;border-bottom:1px solid #21262d;vertical-align:middle}
.ep-list-table tr.ep-row{cursor:pointer}
.ep-list-table tr.ep-row:hover td{background:#1f2937}
/* ── Active panel area ── */
.panel-area{padding:24px}
/* ── Page sections navigation ── */
.page-overview,.page-endpoint{display:none}
.page-overview.active,.page-endpoint.active{display:block}
/* ── Scrollbar ── */
::-webkit-scrollbar{width:6px;height:6px}
::-webkit-scrollbar-track{background:#0d1117}
::-webkit-scrollbar-thumb{background:#30363d;border-radius:3px}
@media(max-width:768px){.sidebar{display:none}.stat-grid{grid-template-columns:repeat(2,1fr)}}
</style>
</head>
<body>

<!-- TOP BAR -->
<header class="topbar">
  <div class="topbar-logo"><span>⚡</span> ${E(scan.title)}</div>
  <div class="topbar-meta">v${E(scan.version || "1.0.0")} · ${E((scan.project.frameworks || []).filter(f => !f.startsWith("CORS")).slice(0,2).join(" · ") || "API")} · ${scan.endpoints.length} endpoints</div>
  <div class="topbar-right">
    <button class="topbar-btn" onclick="showPage('overview')">Overview</button>
    <button class="topbar-btn" onclick="document.getElementById('ep-search').focus()">Search</button>
  </div>
</header>

<!-- LAYOUT -->
<div class="layout">

  <!-- SIDEBAR -->
  <nav class="sidebar">
    <div class="sidebar-search"><input id="ep-search" placeholder="Search endpoints…" oninput="filterNav(this.value)"></div>

    <div class="sb-quick">
      <div class="sidebar-section-title">Quick nav</div>
      <button onclick="showPage('overview')">📊 Overview</button>
      <button onclick="showPage('auth')">🔒 Authentication</button>
      <button onclick="showPage('models')">🗄 Data Models</button>
      <button onclick="showPage('errors')">⚠ Error Reference</button>
      <button onclick="showPage('env')">⚙ Deployment</button>
      <button onclick="showPage('drift')">🔀 Drift Report</button>
    </div>

    <div class="sidebar-section">
      <div class="sidebar-section-title">Endpoints</div>
      <div id="nav-groups">${navGroups}</div>
    </div>
  </nav>

  <!-- MAIN CONTENT -->
  <main class="main">
    <!-- OVERVIEW PAGE -->
    <div id="page-overview" class="page-overview active main-inner">

      <div class="section-card">
        <div class="section-card-head"><div class="section-icon">📊</div><h2>Project Overview</h2></div>
        <div class="section-body">
          <div class="stat-grid">
            <div class="stat-card"><div class="stat-num">${scan.endpoints.length}</div><div class="stat-label">Endpoints</div></div>
            <div class="stat-card"><div class="stat-num">${scan.files.length}</div><div class="stat-label">Files scanned</div></div>
            <div class="stat-card"><div class="stat-num">${Object.keys(byTag).length}</div><div class="stat-label">Resource groups</div></div>
            <div class="stat-card"><div class="stat-num">${scan.endpoints.filter(e => e.authRequired).length}</div><div class="stat-label">Auth-protected</div></div>
          </div>
          <br>
          <table class="param-table">
            <tbody>
              <tr><td style="color:var(--muted);width:140px">Base URL</td><td><code>${E(scan.baseUrl || "http://localhost")}/api</code></td></tr>
              <tr><td style="color:var(--muted)">Framework</td><td>${E((scan.project.frameworks || []).filter(f => !f.startsWith("CORS")).join(", ") || "Unknown")}</td></tr>
              <tr><td style="color:var(--muted)">Languages</td><td>${E((scan.project.languages || []).join(", ") || "Unknown")}</td></tr>
              <tr><td style="color:var(--muted)">Generated</td><td>${E(scan.generatedAt)}</td></tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="section-card">
        <div class="section-card-head"><div class="section-icon">🗂</div><h2>Endpoint Inventory</h2></div>
        <div class="filter-bar">
          ${["","GET","POST","PUT","PATCH","DELETE"].map(m => `<button class="filter-btn${m===""?" active":""}" onclick="filterMethod('${m}',this)">${m||"All"}</button>`).join("")}
          <input class="filter-search" id="tbl-search" placeholder="Filter by path or summary…" oninput="filterTable(this.value)">
        </div>
        <table class="ep-list-table" id="ep-inventory">
          <thead><tr><th>Method</th><th>Path</th><th>Summary</th><th>Controller</th><th>Auth</th><th>Middleware</th></tr></thead>
          <tbody>
            ${scan.endpoints.map((ep, i) => `
            <tr class="ep-row" data-method="${ep.method}" data-path="${E(ep.path)}" data-summary="${E(ep.summary)}" onclick="openEndpoint(${i})">
              <td><span class="badge method ${ep.method}">${ep.method}</span></td>
              <td><code>${E(ep.path)}</code></td>
              <td>${E(ep.summary)}</td>
              <td><small style="color:var(--muted)">${ep.controller ? `${E(ep.controller)}@${E(ep.action)}` : "—"}</small></td>
              <td>${ep.authRequired ? '<span class="req-yes">🔒 Yes</span>' : '<span class="req-no">—</span>'}</td>
              <td><small style="color:var(--muted)">${(ep.middleware || []).map(E).join(", ") || "—"}</small></td>
            </tr>`).join("")}
          </tbody>
        </table>
      </div>

      <div class="section-card">
        <div class="section-card-head"><div class="section-icon">🏷</div><h2>Resource Groups</h2></div>
        <div class="section-body">
          <div class="tag-summary">
            ${Object.entries(byTag).map(([tag, eps]) => `
            <div class="tag-chip" onclick="filterNav('${tag}')">
              <span>${E(tag)}</span>
              <span class="tag-count">${eps.length}</span>
            </div>`).join("")}
          </div>
        </div>
      </div>
    </div>

    <!-- AUTH PAGE -->
    <div id="page-auth" class="page-overview main-inner">
      <div class="section-card">
        <div class="section-card-head"><div class="section-icon">🔒</div><h2>Authentication &amp; Authorization</h2></div>
        <div class="section-body">
          <p style="color:var(--muted);margin-bottom:16px">This API uses <strong style="color:var(--text)">JWT Bearer token</strong> authentication via <code>tymon/jwt-auth</code>. The token is returned on login and must be sent in the <code>Authorization</code> header on every protected request.</p>
          <div class="auth-flow">
            <div class="auth-step">
              <div class="auth-step-num">1</div>
              <div class="auth-step-body">
                <div class="auth-step-title">Register (optional)</div>
                <div class="auth-step-desc"><code>POST /api/users</code> — Create an account with <code>username</code>, <code>email</code>, <code>password</code>. Returns user object with token.</div>
              </div>
            </div>
            <div class="auth-step">
              <div class="auth-step-num">2</div>
              <div class="auth-step-body">
                <div class="auth-step-title">Login</div>
                <div class="auth-step-desc"><code>POST /api/users/login</code> — Submit <code>user.email</code> and <code>user.password</code>. Receive a JWT in <code>user.token</code>.</div>
              </div>
            </div>
            <div class="auth-step">
              <div class="auth-step-num">3</div>
              <div class="auth-step-body">
                <div class="auth-step-title">Attach token</div>
                <div class="auth-step-desc">Include the token in every subsequent request:</div>
              </div>
            </div>
          </div>
          <div class="code-block-wrap" style="margin-top:14px">
            <div class="code-label">Required header</div>
            <pre class="codebox">Authorization: Token &lt;your-jwt-token&gt;</pre>
          </div>
          <br>
          <h3 style="font-size:13px;margin-bottom:10px">Authentication Matrix</h3>
          <table class="param-table">
            <thead><tr><th>Endpoint</th><th>Method</th><th>Auth Required</th><th>Middleware</th></tr></thead>
            <tbody>
              ${scan.endpoints.map(ep => `<tr>
                <td><code>${E(ep.path)}</code></td>
                <td><span class="badge method ${ep.method}">${ep.method}</span></td>
                <td>${ep.authRequired ? '<span class="req-yes">Yes</span>' : '<span class="req-no">No</span>'}</td>
                <td><small style="color:var(--muted)">${(ep.middleware || []).map(E).join(", ") || "—"}</small></td>
              </tr>`).join("")}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- DATA MODELS PAGE -->
    <div id="page-models" class="page-overview main-inner">
      <div class="section-card">
        <div class="section-card-head"><div class="section-icon">🗄</div><h2>Data Models</h2></div>
        <div class="section-body">
          ${[
            {name:"User",table:"users",desc:"Authenticated user entity, implements JWTSubject.",fields:[
              {n:"id",t:"bigint",r:true,d:"Primary key"},
              {n:"username",t:"string(50)",r:true,d:"Unique alphanumeric username"},
              {n:"email",t:"string(255)",r:true,d:"Unique email address"},
              {n:"password",t:"string",r:true,d:"Bcrypt-hashed password (hidden)"},
              {n:"bio",t:"string(255)",r:false,d:"Optional biography"},
              {n:"image",t:"string",r:false,d:"Avatar URL"},
              {n:"created_at",t:"timestamp",r:false,d:"Auto-managed"},
              {n:"updated_at",t:"timestamp",r:false,d:"Auto-managed"}
            ],rels:["hasMany Articles","hasMany Comments","belongsToMany followers (self-referential)"]},
            {name:"Article",table:"articles",desc:"Article entity with slug-based routing and tag support.",fields:[
              {n:"id",t:"bigint",r:true,d:"Primary key"},
              {n:"user_id",t:"bigint",r:true,d:"Author (FK → users)"},
              {n:"slug",t:"string",r:true,d:"Auto-generated unique slug from title"},
              {n:"title",t:"string(255)",r:true,d:"Article title"},
              {n:"description",t:"string(255)",r:true,d:"Short description"},
              {n:"body",t:"text",r:true,d:"Full article content"},
              {n:"created_at",t:"timestamp",r:false,d:"Auto-managed"},
              {n:"updated_at",t:"timestamp",r:false,d:"Auto-managed"}
            ],rels:["belongsTo User","hasMany Comments","belongsToMany Tags","hasMany Favorites"]},
            {name:"Comment",table:"comments",desc:"Comment on an article.",fields:[
              {n:"id",t:"bigint",r:true,d:"Primary key"},
              {n:"user_id",t:"bigint",r:true,d:"Author (FK → users)"},
              {n:"article_id",t:"bigint",r:true,d:"Article (FK → articles)"},
              {n:"body",t:"text",r:true,d:"Comment content"}
            ],rels:["belongsTo User","belongsTo Article"]},
            {name:"Tag",table:"tags",desc:"Global article tags.",fields:[
              {n:"id",t:"bigint",r:true,d:"Primary key"},
              {n:"name",t:"string",r:true,d:"Tag name"}
            ],rels:["belongsToMany Articles"]}
          ].map(m => `
          <div style="margin-bottom:28px">
            <h3 style="font-size:14px;margin-bottom:4px">${E(m.name)} <small style="color:var(--muted);font-size:11px">→ <code>${E(m.table)}</code></small></h3>
            <p style="color:var(--muted);font-size:12px;margin-bottom:8px">${E(m.desc)}</p>
            <table class="param-table">
              <thead><tr><th>Field</th><th>Type</th><th>Required</th><th>Description</th></tr></thead>
              <tbody>
                ${m.fields.map(f => `<tr><td><code>${E(f.n)}</code></td><td>${E(f.t)}</td><td>${f.r ? '<span class="req-yes">Yes</span>' : '<span class="req-no">No</span>'}</td><td>${E(f.d)}</td></tr>`).join("")}
              </tbody>
            </table>
            <div style="margin-top:6px;display:flex;flex-wrap:wrap;gap:6px">
              ${m.rels.map(r => `<span class="pill open">${E(r)}</span>`).join("")}
            </div>
          </div>`).join("")}
        </div>
      </div>
    </div>

    <!-- ERROR REFERENCE PAGE -->
    <div id="page-errors" class="page-overview main-inner">
      <div class="section-card">
        <div class="section-card-head"><div class="section-icon">⚠</div><h2>Error Handling &amp; HTTP Status Codes</h2></div>
        <div class="section-body">
          <table class="error-table">
            <thead><tr><th>Status</th><th>Meaning</th><th>When it occurs</th><th>How to fix</th></tr></thead>
            <tbody>
              ${[
                [200,"OK","Successful GET/PUT/PATCH","—"],
                [201,"Created","Successful POST (resource created)","—"],
                [204,"No content","Successful DELETE","—"],
                [400,"Bad Request","Malformed JSON or missing required field","Check request body format"],
                [401,"Unauthorized","Missing or invalid JWT token","Re-authenticate and attach valid token"],
                [403,"Forbidden","Token is valid but action is not permitted","Ensure the authenticated user owns the resource"],
                [404,"Not Found","Route or resource does not exist","Verify URL and resource ID/slug"],
                [409,"Conflict","Duplicate unique field (email, username)","Use a different value"],
                [422,"Unprocessable Entity","Validation rule failed","Check validation rules in endpoint body docs"],
                [500,"Internal Server Error","Unexpected application error","Check server logs"]
              ].map(([s,m,w,f]) => `<tr>
                <td><span class="status-badge" style="background:${statusColor(s)}20;color:${statusColor(s)};border:1px solid ${statusColor(s)}40">${s}</span></td>
                <td>${m}</td><td>${w}</td><td>${f}</td>
              </tr>`).join("")}
            </tbody>
          </table>
          <br>
          <h3 style="font-size:13px;margin-bottom:8px">Validation Error Format (422)</h3>
          <div class="code-block-wrap">
            <pre class="codebox">{
  "errors": {
    "email": ["The email field is required.", "The email must be a valid email address."],
    "password": ["The password must be at least 6 characters."]
  }
}</pre>
          </div>
        </div>
      </div>
    </div>

    <!-- ENV / DEPLOYMENT PAGE -->
    <div id="page-env" class="page-overview main-inner">
      <div class="section-card">
        <div class="section-card-head"><div class="section-icon">⚙</div><h2>Deployment &amp; Environment</h2></div>
        <div class="section-body">
          <table class="env-table">
            <thead><tr><th>Variable</th><th>Example</th><th>Description</th></tr></thead>
            <tbody>
              ${[
                ["APP_KEY","base64:...","Laravel application key (generate with artisan)"],
                ["APP_ENV","production","Environment: local / production"],
                ["APP_URL","https://api.example.com","Public base URL"],
                ["DB_CONNECTION","mysql","Database driver"],
                ["DB_HOST","127.0.0.1","Database host"],
                ["DB_PORT","3306","Database port"],
                ["DB_DATABASE","realworld","Database name"],
                ["DB_USERNAME","root","Database user"],
                ["DB_PASSWORD","secret","Database password"],
                ["JWT_SECRET","(generated)","JWT signing secret — run: php artisan jwt:secret"],
                ["CORS_ALLOWED_ORIGINS","http://localhost:3000","Comma-separated allowed CORS origins"],
                ["CACHE_DRIVER","file","Cache backend (file / redis)"],
                ["QUEUE_DRIVER","sync","Queue backend (sync / redis)"]
              ].map(([v,e,d]) => `<tr><td><code>${E(v)}</code></td><td><code style="color:var(--muted)">${E(e)}</code></td><td>${E(d)}</td></tr>`).join("")}
            </tbody>
          </table>
          <br>
          <h3 style="font-size:13px;margin-bottom:8px">Dependencies</h3>
          <div style="display:flex;flex-wrap:wrap;gap:6px">
            ${(scan.project.frameworks || []).map(f => `<span class="pill auth">${E(f)}</span>`).join("")}
          </div>
          <br>
          <h3 style="font-size:13px;margin-bottom:8px">Quick Start</h3>
          <div class="code-block-wrap">
            <pre class="codebox">composer install
cp .env.example .env
php artisan key:generate
php artisan jwt:secret
php artisan migrate --seed
php artisan serve</pre>
          </div>
        </div>
      </div>
    </div>

    <!-- DRIFT PAGE -->
    <div id="page-drift" class="page-overview main-inner">
      <div class="section-card">
        <div class="section-card-head"><div class="section-icon">🔀</div><h2>Drift Report</h2></div>
        <div class="section-body">
          <div class="drift-grid">
            <div class="drift-card" style="border-color:#d2992240"><div class="drift-num" style="color:#d29922">${scan.drift.newInCode.length}</div><div class="drift-label">New in code (undocumented)</div></div>
            <div class="drift-card" style="border-color:#f8514940"><div class="drift-num" style="color:#f85149">${scan.drift.removedFromSpec.length}</div><div class="drift-label">Removed from spec</div></div>
            <div class="drift-card" style="border-color:#58a6ff40"><div class="drift-num" style="color:#58a6ff">${scan.drift.changed.length}</div><div class="drift-label">Changed signatures</div></div>
            <div class="drift-card" style="border-color:#3fb95040"><div class="drift-num" style="color:#3fb950">${scan.drift.inSync.length}</div><div class="drift-label">In sync</div></div>
          </div>
        </div>
      </div>
    </div>

    <!-- ENDPOINT DETAIL PAGE -->
    <div id="page-endpoint" class="page-endpoint main-inner">
      <div id="ep-panels">${panels}</div>
    </div>

  </main>
</div>

<script>
const SCAN = JSON.parse("${scanJson}");
let activeMethod = "";

function showPage(name) {
  document.querySelectorAll(".page-overview,.page-endpoint").forEach(p => p.classList.remove("active"));
  const target = document.getElementById("page-" + name);
  if (target) target.classList.add("active");
  document.querySelectorAll(".nav-ep").forEach(b => b.classList.remove("active"));
}

function openEndpoint(idx) {
  showPage("endpoint");
  document.querySelectorAll(".ep-panel").forEach(p => (p.style.display = "none"));
  const panel = document.getElementById("ep-" + idx);
  if (panel) panel.style.display = "block";
  document.querySelectorAll(".nav-ep").forEach(b => {
    b.classList.toggle("active", Number(b.dataset.ep) === idx);
  });
  window.scrollTo(0, 0);
}

window.showEp = openEndpoint;
window.showPage = showPage;

function filterNav(q) {
  const lq = q.toLowerCase();
  document.querySelectorAll(".nav-ep").forEach(btn => {
    const path = btn.querySelector(".nav-path").textContent.toLowerCase();
    const method = btn.querySelector(".nav-method").textContent.toLowerCase();
    btn.style.display = (!lq || path.includes(lq) || method.includes(lq)) ? "" : "none";
  });
  document.querySelectorAll(".nav-group").forEach(g => {
    const visible = [...g.querySelectorAll(".nav-ep")].some(b => b.style.display !== "none");
    g.style.display = visible ? "" : "none";
  });
}

function filterMethod(method, btn) {
  activeMethod = method;
  document.querySelectorAll(".filter-btn").forEach(b => b.classList.remove("active"));
  btn.classList.add("active");
  applyTableFilters();
}

function filterTable(q) { applyTableFilters(q); }

function applyTableFilters(q) {
  const qLower = (q || document.getElementById("tbl-search").value || "").toLowerCase();
  document.querySelectorAll("#ep-inventory tbody tr").forEach(row => {
    const methodMatch = !activeMethod || row.dataset.method === activeMethod;
    const textMatch = !qLower || (row.dataset.path + " " + row.dataset.summary).toLowerCase().includes(qLower);
    row.style.display = methodMatch && textMatch ? "" : "none";
  });
}

document.getElementById("ep-search").addEventListener("input", e => filterNav(e.target.value));

/* Open first endpoint by default */
if (SCAN.endpoints.length > 0) {
  document.getElementById("ep-0") && (document.getElementById("ep-0").style.display = "block");
}
</script>
</body>
</html>`;
}

/* ─────────────────────────────────────────────
   POSTMAN COLLECTION
───────────────────────────────────────────── */
function toPostman(scan) {
  const baseUrl = (scan.baseUrl || "http://localhost") + "/api";
  const groups = {};
  for (const ep of scan.endpoints) {
    const tag = (ep.tags || ["other"])[0];
    (groups[tag] = groups[tag] || []).push(ep);
  }

  return {
    info: {
      name: `${scan.title || "API"} v${scan.version || "1.0.0"}`,
      description: scan.description || "",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    auth: { type: "bearer", bearer: [{ key: "token", value: "{{jwt_token}}", type: "string" }] },
    variable: [
      { key: "baseUrl", value: baseUrl, type: "string" },
      { key: "jwt_token", value: "", type: "string" }
    ],
    item: Object.entries(groups).map(([tag, eps]) => ({
      name: tag.charAt(0).toUpperCase() + tag.slice(1),
      item: eps.map(ep => {
        const bodyFields = Object.entries(ep.request.body?.schema?.properties || {});
        const sampleBody = bodyFields.length
          ? { [ep.tags[0] || "data"]: Object.fromEntries(bodyFields.map(([n, f]) => [n, f.example !== undefined ? f.example : f.type])) }
          : null;

        return {
          name: ep.summary || `${ep.method} ${ep.path}`,
          request: {
            method: ep.method,
            header: [
              { key: "Content-Type", value: "application/json", type: "text" },
              ...(ep.authRequired ? [{ key: "Authorization", value: "Token {{jwt_token}}", type: "text" }] : []),
              ...ep.request.headers.filter(h => !/authorization/i.test(h.name)).map(h => ({ key: h.name, value: h.format || "", type: "text" }))
            ],
            url: {
              raw: `{{baseUrl}}${ep.path.replace(/\{([^}]+)\}/g, ":$1")}`,
              host: ["{{baseUrl}}"],
              path: ep.path.split("/").filter(Boolean),
              query: ep.request.queryParams.map(q => ({ key: q.name, value: "", description: q.description, disabled: true }))
            },
            body: sampleBody && ["POST", "PUT", "PATCH"].includes(ep.method) ? {
              mode: "raw",
              raw: JSON.stringify(sampleBody, null, 2),
              options: { raw: { language: "json" } }
            } : undefined,
            description: [
              ep.description,
              ep.controller ? `Controller: ${ep.controller}@${ep.action}` : "",
              ep.middleware && ep.middleware.length ? `Middleware: ${ep.middleware.join(", ")}` : ""
            ].filter(Boolean).join("\n\n")
          },
          response: []
        };
      })
    }))
  };
}

/* ─────────────────────────────────────────────
   YAML SERIALISER (minimal, no deps)
───────────────────────────────────────────── */
function toYaml(value, indent = 0) {
  const pad = " ".repeat(indent);
  if (value === null || value === undefined) return "null";
  if (typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (!value.length) return "[]";
    return value.map(item =>
      `${pad}- ${typeof item === "object" && item !== null ? "\n" + toYaml(item, indent + 2) : toYaml(item, 0)}`
    ).join("\n");
  }
  const entries = Object.entries(value).filter(([, v]) => v !== undefined);
  if (!entries.length) return "{}";
  return entries.map(([key, v]) => {
    const safeKey = /^[A-Za-z0-9_.-]+$/.test(key) ? key : JSON.stringify(key);
    if (typeof v === "object" && v !== null && !(Array.isArray(v) && !v.length)) {
      return `${pad}${safeKey}:\n${toYaml(v, indent + 2)}`;
    }
    return `${pad}${safeKey}: ${toYaml(v, 0)}`;
  }).join("\n");
}

function escapeHtml(text) {
  return String(text).replace(/[&<>"']/g, c => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
  }[c]));
}

function statusColor(s) {
  if (s < 300) return "#16a34a";
  if (s < 400) return "#0369a1";
  if (s < 500) return "#d97706";
  return "#dc2626";
}

module.exports = { renderAll, toOpenApi };
